/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< Updated upstream
=======
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
>>>>>>> Stashed changes
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< Updated upstream
=======
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
>>>>>>> Stashed changes
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
<<<<<<< Updated upstream
=======
  '/clients/': typeof ClientsIndexRoute
>>>>>>> Stashed changes
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books': typeof BooksIndexRoute
<<<<<<< Updated upstream
=======
  '/clients': typeof ClientsIndexRoute
>>>>>>> Stashed changes
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
<<<<<<< Updated upstream
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/books' | '/books/$bookId' | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/books/$bookId' | '/books'
  id: '__root__' | '/' | '/about' | '/books' | '/books/$bookId' | '/books/'
=======
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/clients'
    | '/books/$bookId'
    | '/clients/$clientId'
    | '/books/'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books/$bookId'
    | '/clients/$clientId'
    | '/books'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/clients'
    | '/books/$bookId'
    | '/clients/$clientId'
    | '/books/'
    | '/clients/'
>>>>>>> Stashed changes
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRouteWithChildren
<<<<<<< Updated upstream
=======
  ClientsRoute: typeof ClientsRouteWithChildren
>>>>>>> Stashed changes
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< Updated upstream
=======
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
>>>>>>> Stashed changes
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

<<<<<<< Updated upstream
=======
interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

>>>>>>> Stashed changes
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRouteWithChildren,
<<<<<<< Updated upstream
=======
  ClientsRoute: ClientsRouteWithChildren,
>>>>>>> Stashed changes
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
